#!/usr/bin/env bash
echo "Disabling Windows Explorer shell integration."
cp /usr/share/wlinux/ShellIntegration/Install.reg $(wslupath -T)/Uninstall.reg
cmd.exe /C 'Reg import %TEMP%\Uninstall.reg'
cmd.exe /C 'del %TEMP%\Uninstall.reg'
